language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - angela_ybr@hotmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS bd;'
script:
#Test unitario y de integracion en develop
- mvn verify 
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify 
- mvn sonar:sonar -Dsonar.organization=asancgom-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR 